# Generated by Django 6.0.5 on 2026-05-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='endet_at',
            new_name='ended_at',
        ),
    ]
